version: '3'

services:
  postgres:
    container_name: management_system
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: management_system
    ports:
      - "5432:5432"